---
- name: Upgrade the system
  apt:
    update_cache: true
    upgrade: dist
  register: apt_cache
  retries: 50
  until: apt_cache is success

- name: Install system required packages
  apt:
    pkg:
      - ntp
      - python3
      - python3-apt
      - curl
      - apt-transport-https
      - software-properties-common
      - wget
      - git
      - build-essential
      - haveged
      - python3-openssl
      - jq
      - rsync
      - htop
      - mtr-tiny
      - file
      - lsof
      - tcpdump
      - acl
      - unzip
    state: present

- name: Set timezone to UTC
  timezone:
    name: UTC
